In [1]:
import numpy as np

In [2]:
a = np.arange(1, 5, 1, dtype='int')
print(a)
print(a + 1) # 对每一位都进行了运算
print(2 ** a)

[1 2 3 4]
[2 3 4 5]
[ 2  4  8 16]


In [3]:
b = np.ones(4) + 1
print(b)
print(a - b)  # 按位减法
print(a * b)  # 按位乘法

j = np.arange(5)
print(2 ** (j + 1) - j)

[ 2.  2.  2.  2.]
[-1.  0.  1.  2.]
[ 2.  4.  6.  8.]
[ 2  3  6 13 28]


In [4]:
# benchmarks array
a = np.arange(10000)
%timeit a + 1

The slowest run took 39.00 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 8.61 µs per loop


In [5]:
# benchmarks list, x100 slower 
l = range(10000)
%timeit [i + 1 for i in l]

1000 loops, best of 3: 787 µs per loop


In [6]:
#! 向量乘法dot
c = np.ones((3, 3))
print(c * c) # 不是向量乘法，按位乘法
print(c.dot(c)) # 向量乘法

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
[[ 3.  3.  3.]
 [ 3.  3.  3.]
 [ 3.  3.  3.]]


In [7]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
print(a == b)  # bool array
print(a > b)   # bool array
print(np.array_equal(a, b))  # bool value

[False  True False  True]
[False False  True False]
False


In [8]:
# logic operation
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
print(np.logical_or(a, b))  # 按位逻辑或运算
print(np.logical_and(a, b)) # 按位逻辑与运算

[ True  True  True False]
[ True False False False]


In [9]:
# 超越函数
a = np.arange(5)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
[       -inf  0.          0.69314718  1.09861229  1.38629436]
[  1.           2.71828183   7.3890561   20.08553692  54.59815003]


/home/yabinzhang/.pyenv/versions/3.5.0/lib/python3.5/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log
  after removing the cwd from sys.path.


In [10]:
# shape mismatches error!
# transposition 转制
a = np.triu(np.ones((3, 3)), 1) # view no copy
print(a)
print(a.T)

[[ 0.  1.  1.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]
[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 1.  1.  0.]]


In [11]:
np.triu?

In [12]:
x = np.array([1, 2, 3, 4])
print(np.sum(x))
print(x.sum())

10
10


In [13]:
x = np.array([[1, 1], [2, 2]])
print(x)
print(x.sum(axis=0))
print(x.sum(axis=1))
print(x[:, 0].sum(), x[:, 1].sum())

[[1 1]
 [2 2]]
[3 3]
[2 4]
3 3


In [14]:
np.sum?

In [15]:
x, x.max(), x.min(), x.argmax(), x.argmin()

(array([[1, 1],
        [2, 2]]), 2, 1, 2, 0)

In [16]:
x = np.array([True, True, False])
np.all(x), np.any(x)

(False, True)

In [17]:
a = np.zeros((100, 100))
print(np.any(a != 0))
print(np.all(a == a))

False
True


In [18]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean(), np.median(x), x.std(), np.median(y, axis=-1) # last axis

(1.75, 1.5, 0.82915619758884995, array([ 2.,  5.]))

![Boradcasting](http://www.scipy-lectures.org/_images/numpy_broadcasting.png)

In [19]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
print(a) # broadcasting
b = np.array([0, 1, 2])
print(a + b) # broadcasting

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [20]:
a = np.ones((4, 5))
a[0] = 2  # boradcasting, 把0维数组赋值给一个一维数组
print(a)

[[ 2.  2.  2.  2.  2.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [21]:
a = np.arange(0, 40, 10)
print(a.shape)
a = a[:, np.newaxis] # adds a new axis => 2D array
print(a.shape)
print(a)
print(a + b)  # b = arrray([0, 1, 2])

(4,)
(4, 1)
[[ 0]
 [10]
 [20]
 [30]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [22]:
a= np.array([1, 2, 3, 4, 5])
print(a[:, np.newaxis])
print(np.abs(a - a[:, np.newaxis]))

[[1]
 [2]
 [3]
 [4]
 [5]]
[[0 1 2 3 4]
 [1 0 1 2 3]
 [2 1 0 1 2]
 [3 2 1 0 1]
 [4 3 2 1 0]]


In [23]:
# np.ogrid? for broadcasting
np.ogrid[0:5, 0:5]

[array([[0],
        [1],
        [2],
        [3],
        [4]]), array([[0, 1, 2, 3, 4]])]

In [24]:
# np.mgrid, directly return matrix
x, y = np.mgrid[0:4, 0:4]

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ravel())  # flattening
print(a.T)  # 转制
print(a.T.ravel()) # 先转制，再摊平

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[1 4 2 5 3 6]


In [26]:
print(a.shape)  # return matrix type
b = a.ravel()
b = b.reshape((2, 3))
print(b)
print(np.may_share_memory(a, b))
print(np.equal(a, b))  # shared
print(np.array_equiv(a, b))

print(a.reshape((2, -1)))  # unspecified (-1) value is isferred,未指明的-1指示此值需推测

(2, 3)
[[1 2 3]
 [4 5 6]]
True
[[ True  True  True]
 [ True  True  True]]
True
[[1 2 3]
 [4 5 6]]


In [27]:
np.lookfor('array equal')

Search results for 'array equal'
--------------------------------
numpy.array_equiv
    Returns True if input arrays are shape consistent and all elements equal.
numpy.isclose
    Returns a boolean array where two arrays are element-wise equal within a
numpy.allclose
    Returns True if two arrays are element-wise equal within a tolerance.
numpy.tensordot
    Compute tensor dot product along specified axes for arrays >= 1-D.
numpy.ma.masked_equal
    Mask an array where equal to a given value.
numpy.ma.allclose
    Returns True if two arrays are element-wise equal within a tolerance.
numpy.ma.mask_cols
    Mask columns of a 2D array that contain masked values.
numpy.ma.mask_rows
    Mask rows of a 2D array that contain masked values.
numpy.ma.masked_not_equal
    Mask an array where `not` equal to a given value.
numpy.ma.intersect1d
    Returns the unique elements common to both arrays.
numpy.ma.masked_less_equal
    Mask an array where less than or equal to a given value.
numpy.testin

In [28]:
# Beware reshape may also return a copy!
a = np.zeros((3, 2))
b = a.T.reshape(3 * 2)
b[0] = 9
print(a)  # no change?!
# isn't shared! need learn more about the memory layout of a numpy array
print(np.may_share_memory(a, b))

[[ 0.  0.]
 [ 0.  0.]
 [ 0.  0.]]
False


In [29]:
# add a dimension
z = np.array([1, 2, 3])
print(z)
print(z[:, np.newaxis])  # 纵向增加一个维度
tz = z[:, np.newaxis]
print(tz[:, np.newaxis])  # 纵向再增加一个
print(z[np.newaxis, :])  # 横向增加一个维度

[1 2 3]
[[1]
 [2]
 [3]]
[[[1]]

 [[2]]

 [[3]]]
[[1 2 3]]


In [30]:
# dimension shuffling
a = np.arange(4*3*2).reshape(4, 3, 2)
print(a.shape)
print(a[0, 2, 1])
# print(a)
b = a.transpose(1, 2, 0)
print(b[2, 1, 0])

(4, 3, 2)
5
5


In [31]:
np.transpose?

In [32]:
# resize
a = np.arange(4)
a.resize((8,))
print(a)

[0 1 2 3 0 0 0 0]


In [33]:
# sorting data
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
print(j)  # j 中保存的是排序后索引
print(a[j])

# for minima and maxima
j_max = np.argmax(a)
j_min = np.argmin(a)
print(j_max, j_min, a[j_max], a[j_min])

[2 3 1 0]
[1 2 3 4]
0 2 4 1
